/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.taliyams;

import com.taliyams.models.MainPage;
import com.taliyams.models.password.DataPassword;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        DataPassword.loadCSVData();
        MainPage mainPage = new MainPage("Password Vault", 80);
        mainPage.draw();
    }
}
